import type { CollectionConfig } from 'payload'

export const Articles: CollectionConfig = {
  slug: 'articles',
  admin: {
    useAsTitle: 'title',
    defaultColumns: ['title', 'language', 'status', 'published_at'],
  },
  access: {
    read: () => true,
  },
  fields: [
    {
      name: 'title',
      type: 'text',
      required: true,
    },
    {
      name: 'slug',
      type: 'text',
      required: true,
      unique: true,
      admin: {
        description: 'Auto-generated from title, URL-safe',
      },
    },
    {
      name: 'language',
      type: 'select',
      required: true,
      options: [
        { label: 'English', value: 'en' },
        { label: 'German', value: 'de' },
        { label: 'French', value: 'fr' },
      ],
      defaultValue: 'en',
    },
    {
      name: 'status',
      type: 'select',
      required: true,
      options: [
        { label: 'Draft', value: 'draft' },
        { label: 'Review (Bot - awaiting approval)', value: 'review' },
        { label: 'Published', value: 'published' },
        { label: 'Archived', value: 'archived' },
      ],
      defaultValue: 'draft',
    },
    {
      name: 'published_at',
      type: 'date',
      admin: {
        date: {
          pickerAppearance: 'dayAndTime',
        },
      },
    },
    {
      name: 'category',
      type: 'relationship',
      relationTo: 'categories',
      required: true,
    },
    {
      name: 'author',
      type: 'relationship',
      relationTo: 'authors',
    },
    {
      name: 'summary',
      type: 'textarea',
      admin: {
        description: '100-150 words, keyword-rich. Shown in listings and meta description.',
      },
    },
    {
      name: 'content',
      type: 'richText',
      admin: {
        description: 'Full article body, 500-800 words, original rewrite.',
      },
    },
    {
      name: 'what_this_means',
      type: 'textarea',
      admin: {
        description: 'Analysis section: impact and implications for the reader.',
      },
    },
    {
      name: 'key_points',
      type: 'array',
      admin: {
        description: 'Bullet points with optional internal links.',
      },
      fields: [
        {
          name: 'point',
          type: 'text',
          required: true,
        },
        {
          name: 'link',
          type: 'text',
          admin: {
            description: 'Optional internal link URL',
          },
        },
      ],
    },
    {
      name: 'image',
      type: 'text',
      admin: {
        description: 'Cloudinary URL - min 1200x628px, WebP',
      },
    },
    {
      name: 'image_alt',
      type: 'text',
      admin: {
        description: 'SEO alt text for the image',
      },
    },
    {
      name: 'tags',
      type: 'array',
      fields: [
        {
          name: 'tag',
          type: 'text',
          required: true,
        },
      ],
    },
    {
      name: 'source_url',
      type: 'text',
      required: true,
      admin: {
        description: 'Original news source URL - required to avoid copyright issues',
      },
    },
    {
      name: 'source_name',
      type: 'text',
      admin: {
        description: 'e.g. Reuters, TechCrunch, Deutsche Welle',
      },
    },
    {
      name: 'seo_title',
      type: 'text',
      admin: {
        description: '50-60 characters, keyword-optimized',
      },
    },
    {
      name: 'seo_description',
      type: 'textarea',
      admin: {
        description: '150-160 characters for meta description',
      },
    },
    {
      name: 'schema_markup',
      type: 'json',
      admin: {
        description: 'JSON-LD schema (NewsArticle type) - auto-generated by bot',
      },
    },
    {
      name: 'internal_links',
      type: 'array',
      admin: {
        description: 'Related articles for internal linking',
      },
      fields: [
        {
          name: 'label',
          type: 'text',
          required: true,
        },
        {
          name: 'url',
          type: 'text',
          required: true,
        },
      ],
    },
  ],
}
